name: Deploy Flutter App to Oracle Cloud VM

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.14.0

        # Use the webfactory/ssh-agent action to add the SSH key
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Flutter dependencies
        run: |
          cd fire_app  # Navigate to the fire_app directory
          flutter pub get  # Install the dependencies

      - name: Build Flutter Web
        run: |
          cd fire_app  # Navigate to the fire_app directory
          flutter build web  # Build the web app

      - name: Deploy to Oracle Cloud VM
        run: |
          tar -czf /tmp/build.tar.gz -C fire_app/build/web .  # Archive the build files
          scp -o StrictHostKeyChecking=no /tmp/build.tar.gz opc@${{ secrets.VM_IP_ADDRESS }}:/tmp/
          ssh opc@${{ secrets.VM_IP_ADDRESS }} 'sudo tar -xzf /tmp/build.tar.gz -C /usr/share/nginx/html/ && sudo systemctl restart nginx'
