name: Deploy Flutter App to Oracle Cloud VM

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.14.0

      - name: Create SSH key file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa

      - name: Install Flutter dependencies
        run: |
          cd fire_app  # Navigate to the fire_app directory
          flutter pub get  # Install the dependencies

      - name: Build Flutter Web
        run: |
          cd fire_app  # Navigate to the fire_app directory
          flutter build web  # Build the web app

      - name: Deploy to Oracle Cloud VM
        run: |
          scp -i /home/runner/.ssh/id_rsa -o StrictHostKeyChecking=no -r fire_app/build/web/* opc@${{ secrets.VM_IP_ADDRESS }}:/var/www/html/
          ssh -i /home/runner/.ssh/id_rsa -o StrictHostKeyChecking=no opc@${{ secrets.VM_IP_ADDRESS }} 'sudo systemctl restart nginx'
